class AtomIdentifier:
    def __init__(self):
        self.names = []
        self.abbreviations = []
        self.atomic_numbers = []

    def add(self, name, abbreviation, atomic_number):
        assert isinstance(name, str), "Name has to be a string"
        assert isinstance(abbreviation, str), "The abbreviation has to be a string"
        assert isinstance(atomic_number, int), "The atomic number has to be an integer"
        assert len(abbreviation) <= 2, "The abbreviation has a wrong length (<= 2 is expected)"
        self.names.append(name)
        self.abbreviations.append(abbreviation)
        self.atomic_numbers.append(atomic_number)

atom_identifier = AtomIdentifier()
atom_identifier.add("Hydrogen","H",1)
atom_identifier.add("Helium","He",2)
atom_identifier.add("Lithium","Li",3)
atom_identifier.add("Beryllium","Be",4)
atom_identifier.add("Boron","B",5)
atom_identifier.add("Carbon","C",6)
atom_identifier.add("Nitrogen","N",7)
atom_identifier.add("Oxygen","O",8)
atom_identifier.add("Fluorine","F",9)
atom_identifier.add("Neon","Ne",10)
atom_identifier.add("Sodium","Na",11)
atom_identifier.add("Magnesium","Mg",12)
atom_identifier.add("Aluminium","Al",13)
atom_identifier.add("Silicon","Si",14)
atom_identifier.add("Phosphorus","P",15)
atom_identifier.add("Sulfur","S",16)
atom_identifier.add("Chlorine","Cl",17)
atom_identifier.add("Argon","Ar",18)
atom_identifier.add("Potassium","K",19)
atom_identifier.add("Calcium","Ca",20)
atom_identifier.add("Scandium","Sc",21)
atom_identifier.add("Titanium","Ti",22)
atom_identifier.add("Vanadium","V",23)
atom_identifier.add("Chromium","Cr",24)
atom_identifier.add("Manganese","Mn",25)
atom_identifier.add("Iron","Fe",26)
atom_identifier.add("Cobalt","Co",27)
atom_identifier.add("Nickel","Ni",28)
atom_identifier.add("Copper","Cu",29)
atom_identifier.add("Zinc","Zn",30)
atom_identifier.add("Gallium","Ga",31)
atom_identifier.add("Germanium","Ge",32)
atom_identifier.add("Arsenic","As",33)
atom_identifier.add("Selenium","Se",34)
atom_identifier.add("Bromine","Br",35)
atom_identifier.add("Krypton","Kr",36)
atom_identifier.add("Rubidium","Rb",37)
atom_identifier.add("Strontium","Sr",38)
atom_identifier.add("Yttrium","Y",39)
atom_identifier.add("Zirconium","Zr",40)
atom_identifier.add("Niobium","Nb",41)
atom_identifier.add("Molybdenum","Mo",42)
atom_identifier.add("Technetium","Tc",43)
atom_identifier.add("Ruthenium","Ru",44)
atom_identifier.add("Rhodium","Rh",45)
atom_identifier.add("Palladium","Pd",46)
atom_identifier.add("Silver","Ag",47)
atom_identifier.add("Cadmium","Cd",48)
atom_identifier.add("Indium","In",49)
atom_identifier.add("Tin","Sn",50)
atom_identifier.add("Antimony","Sb",51)
atom_identifier.add("Tellurium","Te",52)
atom_identifier.add("Iodine","I",53)
atom_identifier.add("Xenon","Xe",54)
atom_identifier.add("Caesium","Cs",55)
atom_identifier.add("Barium","Ba",56)
atom_identifier.add("Lanthanum","La",57)
atom_identifier.add("Cerium","Ce",58)
atom_identifier.add("Praseodymium","Pr",59)
atom_identifier.add("Neodymium","Nd",60)
atom_identifier.add("Promethium","Pm",61)
atom_identifier.add("Samarium","Sm",62)
atom_identifier.add("Europium","Eu",63)
atom_identifier.add("Gadolinium","Gd",64)
atom_identifier.add("Terbium","Tb",65)
atom_identifier.add("Dysprosium","Dy",66)
atom_identifier.add("Holmium","Ho",67)
atom_identifier.add("Erbium","Er",68)
atom_identifier.add("Thulium","Tm",69)
atom_identifier.add("Ytterbium","Yb",70)
atom_identifier.add("Lutetium","Lu",71)
atom_identifier.add("Hafnium","Hf",72)
atom_identifier.add("Tantalum","Ta",73)
atom_identifier.add("Tungsten","W",74)
atom_identifier.add("Rhenium","Re",75)
atom_identifier.add("Osmium","Os",76)
atom_identifier.add("Iridium","Ir",77)
atom_identifier.add("Platinum","Pt",78)
atom_identifier.add("Gold","Au",79)
atom_identifier.add("Mercury","Hg",80)
atom_identifier.add("Thallium","Tl",81)
atom_identifier.add("Lead","Pb",82)
atom_identifier.add("Bismuth","Bi",83)
atom_identifier.add("Polonium","Po",84)
atom_identifier.add("Astatine","At",85)
atom_identifier.add("Radon","Rn",86)
atom_identifier.add("Francium","Fr",87)
atom_identifier.add("Radium","Ra",88)
atom_identifier.add("Actinium","Ac",89)
atom_identifier.add("Thorium","Th",90)
atom_identifier.add("Protactinium","Pa",91)
atom_identifier.add("Uranium","U",92)
atom_identifier.add("Neptunium","Np",93)
atom_identifier.add("Plutonium","Pu",94)
atom_identifier.add("Americium","Am",95)
atom_identifier.add("Curium","Cm",96)
atom_identifier.add("Berkelium","Bk",97)
atom_identifier.add("Californium","Cf",98)
atom_identifier.add("Einsteinium","Es",99)
atom_identifier.add("Fermium","Fm",100)
atom_identifier.add("Mendelevium","Md",101)
atom_identifier.add("Nobelium","No",102)
atom_identifier.add("Lawrencium","Lr",103)
atom_identifier.add("Rutherfordium","Rf",104)
atom_identifier.add("Dubnium","Db",105)
atom_identifier.add("Seaborgium","Sg",106)
atom_identifier.add("Bohrium","Bh",107)
atom_identifier.add("Hassium","Hs",108)
atom_identifier.add("Meitnerium","Mt",109)
atom_identifier.add("Darmstadtium","Ds",110)
atom_identifier.add("Roentgenium","Rg",111)
atom_identifier.add("Copernicium","Cn",112)
atom_identifier.add("Nihonium","Nh",113)
atom_identifier.add("Flerovium","Fl",114)
atom_identifier.add("Moscovium","Mc",115)
atom_identifier.add("Livermorium","Lv",116)
atom_identifier.add("Tennessine","Ts",117)
atom_identifier.add("Oganesson","Og",118)
